apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-handson-app
  namespace: dev-handson-app
spec:
  project: default
  source:
    repoURL: "https://github.com/openshift-pipelines-gitops-practice/app-manifests.git"
    targetRevision: main
    path: envs/dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev-handson-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
