apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: dev-handson-backend-gitlab
  namespace: dev-handson-app
spec:
  url: "https://gitlab.apps.cluster-9qtcm.9qtcm.sandbox1494.opentlc.com/openshift-pipelines-gitops-practice/backend-app"
  git_provider:
    secret:
      name: "gitlab-webhook-config"
      key: "provider.token"
    webhook_secret:
      name: "gitlab-webhook-config"
      key: "webhook.secret"
